# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spire < Formula
  desc "Coordination hub for AI agents across repositories"
  homepage "https://github.com/awell-health/spire"
  version "0.20.2"
  license "Apache-2.0"

  depends_on "beads"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/awell-health/spire/releases/download/v0.20.2/spire_darwin_amd64.tar.gz"
      sha256 "fba1eb471aab0ec27b8d6712b53044cb891a1f21ec36ebff5f611bce1ba459cb"

      define_method(:install) do
        bin.install "spire"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/awell-health/spire/releases/download/v0.20.2/spire_darwin_arm64.tar.gz"
      sha256 "9e22c2275e22b7ba8807dc6c68872562bcc017107da8b1725eee41cb2d6a119d"

      define_method(:install) do
        bin.install "spire"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/awell-health/spire/releases/download/v0.20.2/spire_linux_amd64.tar.gz"
      sha256 "231dada6e2a5acfe49614358cac41e06bb1df67116714b97efcbd2e1de1fb445"
      define_method(:install) do
        bin.install "spire"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/awell-health/spire/releases/download/v0.20.2/spire_linux_arm64.tar.gz"
      sha256 "0137f595a110022f90f3f48516fe96566944ad7e5908633535268704dad65a70"
      define_method(:install) do
        bin.install "spire"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with Spire:
        1. Create a tower:    spire tower create --name my-team
        2. Register a repo:   cd ~/your-repo && spire repo add
        3. Start services:    spire up
        4. File your first task: spire file "My first task" -t task -p 2

      For AI agents:
        spire summon 3                       # Summon wizards to work ready beads
        spire summon 1 --targets spi-abc     # Target a specific bead
        spire board --json                   # Machine-readable board state
        spire roster --json                  # Agent status as JSON
        spire collect --json                 # Check agent inbox

      Docs: https://github.com/awell-health/spire
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/spire version")
  end
end
