# This file was generated by GoReleaser. DO NOT EDIT.
cask "spire" do
  version "0.34.2"

  on_macos do
    on_intel do
      url "https://github.com/awell-health/spire/releases/download/v#{version}/spire_darwin_amd64.tar.gz"
      sha256 "26285a068b3c80677e2e4de1590bb1df88c066113a93c9f06722eaa55994d555"
    end
    on_arm do
      url "https://github.com/awell-health/spire/releases/download/v#{version}/spire_darwin_arm64.tar.gz"
      sha256 "9c17533cdfb23a6f629eef9c55fa1ab86b02b2400a35829f99e9a2cbdc84e11b"
    end
  end

  name "spire"
  desc "Coordination hub for AI agents across repositories"
  homepage "https://github.com/awell-health/spire"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "beads",
    ]

  binary "spire"

  # No zap stanza required

  caveats <<~EOS
    To get started with Spire:
      1. Create a tower:    spire tower create --name my-team
      2. Register a repo:   cd ~/your-repo && spire repo add
      3. Start services:    spire up
      4. File your first task: spire file "My first task" -t task -p 2
  EOS
end
