# This file was generated by GoReleaser. DO NOT EDIT.
cask "spire" do
  version "0.34.0"

  on_macos do
    on_intel do
      url "https://github.com/awell-health/spire/releases/download/v#{version}/spire_darwin_amd64.tar.gz"
      sha256 "26b6ba489e5b29e10430d37cbae43a67c4165ef57eb4d7108153edca9b6f9c42"
    end
    on_arm do
      url "https://github.com/awell-health/spire/releases/download/v#{version}/spire_darwin_arm64.tar.gz"
      sha256 "e69cdb28ed75eb5ea2f5458b40624341b9e02b5e1d9f6168e9519db302511d19"
    end
  end

  name "spire"
  desc "Coordination hub for AI agents across repositories"
  homepage "https://github.com/awell-health/spire"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "beads",
    ]

  binary "spire"

  # No zap stanza required

  caveats <<~EOS
    To get started with Spire:
      1. Create a tower:    spire tower create --name my-team
      2. Register a repo:   cd ~/your-repo && spire repo add
      3. Start services:    spire up
      4. File your first task: spire file "My first task" -t task -p 2
  EOS
end
