# This file was generated by GoReleaser. DO NOT EDIT.
cask "spire" do
  version "0.34.1"

  on_macos do
    on_intel do
      url "https://github.com/awell-health/spire/releases/download/v#{version}/spire_darwin_amd64.tar.gz"
      sha256 "d18675af916c351f72648efa79c24bf87ca9691b0be3707538f23b9b3811d2bd"
    end
    on_arm do
      url "https://github.com/awell-health/spire/releases/download/v#{version}/spire_darwin_arm64.tar.gz"
      sha256 "0ff84ff8588e7632d8c4a4d75d3a1df61b52958f4e53e3d1c9fb7f90fc4dec63"
    end
  end

  name "spire"
  desc "Coordination hub for AI agents across repositories"
  homepage "https://github.com/awell-health/spire"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "beads",
    ]

  binary "spire"

  # No zap stanza required

  caveats <<~EOS
    To get started with Spire:
      1. Create a tower:    spire tower create --name my-team
      2. Register a repo:   cd ~/your-repo && spire repo add
      3. Start services:    spire up
      4. File your first task: spire file "My first task" -t task -p 2
  EOS
end
